# Generated by Django 4.0.3 on 2022-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
