# Generated by Django 4.0.3 on 2022-03-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author', max_length=200),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='genre', help_text='Select a genre for this book', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='language', max_length=300),
        ),
    ]
