# Generated by Django 4.0.3 on 2022-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author_remove_book_genre_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
